command:
  - "streamlit"
  - "run"
  - "app/streamlit_app.py"

env:
  - name: DATABRICKS_SQL_WAREHOUSE_ID
    value: "ef7f63b5aa1f7b07"
    valueFrom: sql-warehouse
  - name: ALPHA_VANTAGE_API_KEY
    value: "GPHS1GXG9P6BPN9X"
    valueFrom: secret

resources:
  - files:
      - source_path: requirements.txt
  - name: sql-warehouse
    type: sql_warehouse
  - name: secret
    type: secret
    key: alpha-vantage-api-key
